MySqlUrl: root:123456@tcp(127.0.0.1:3306)/instaloader?charset=utf8mb4&parseTime=True&loc=Local
MySqlMaxIdle: 5
MySqlMaxOpen: 10

RedisCache:
  Host: [ "127.0.0.1:6379" ]
  DB: 1
  Password:
  MaxIdle: 100
  MaxActive: 500